version: '3'

services:
  node-app:
    build: .
    image: node-app
    environment:
      # - MONGODB_URL=mongodb://mongodb:27017/Limousine
      - MONGODB_URL==mongodb+srv://hidayat:admin123@atlascluster.1isky2l.mongodb.net/?retryWrites=true&w=majority&appName=AtlasCluster
    ports:
      - '9000:9000'
    depends_on:
      - mongodb
    volumes:
      - .:/usr/src/node-app
    networks:
      - node-network

  mongodb:
    image: mongo:4.2.1-bionic
    ports:
      - '27017:27017'
    volumes:
      - dbdata:/data/db
    networks:
      - node-network

volumes:
  dbdata:

networks:
  node-network:
    driver: bridge
